# Generated by Django 3.0.3 on 2020-06-09 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seatbooking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookseats',
            name='alert_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bookseats',
            name='expiry_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bookseats',
            name='hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookseats',
            name='idletime',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookseats',
            name='leader',
            field=models.CharField(default='archit', max_length=9),
        ),
        migrations.AddField(
            model_name='bookseats',
            name='other',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookseats',
            name='overnight',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookseats',
            name='seatbooked',
            field=models.CharField(default='A1', max_length=5),
        ),
        migrations.AddField(
            model_name='multipleseats',
            name='clubbed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seats',
            name='hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seats',
            name='idled_till',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='seats',
            name='owner',
            field=models.CharField(default='archit', max_length=50),
        ),
        migrations.AddField(
            model_name='seats',
            name='owner_roll',
            field=models.CharField(default='archit', max_length=9),
        ),
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=50)),
                ('roll', models.CharField(max_length=9)),
                ('seatname', models.CharField(max_length=5)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='new_notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='hideidentity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hide', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
