# Generated by Django 3.0.3 on 2020-06-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seatbooking', '0002_auto_20200609_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookseats',
            name='leader',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='bookseats',
            name='seatbooked',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='seats',
            name='owner',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='seats',
            name='owner_roll',
            field=models.CharField(max_length=9),
        ),
        migrations.DeleteModel(
            name='hideidentity',
        ),
    ]
