# Generated by Django 3.0.3 on 2020-06-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seatbooking', '0003_auto_20200609_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seats',
            name='owner',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='seats',
            name='owner_roll',
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
