# Generated by Django 3.0.3 on 2020-06-12 14:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('seatbooking', '0004_auto_20200610_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seats',
            name='idled_till',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
