# Generated by Django 3.0.3 on 2020-05-13 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibAdmin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='passkey',
        ),
    ]
