# Generated by Django 3.0.3 on 2020-05-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibAdmin', '0003_authenticate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticate',
            name='login',
            field=models.BooleanField(),
        ),
    ]
