# Generated by Django 3.0.3 on 2020-05-15 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibAdmin', '0005_auto_20200515_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticate',
            name='login',
            field=models.BooleanField(),
        ),
    ]
