# Generated by Django 3.0.3 on 2020-07-09 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibAdmin', '0008_timedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticate',
            name='login',
            field=models.BooleanField(default=False),
        ),
    ]
