# Generated by Django 3.0.3 on 2020-06-15 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_gadget_taken'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='messages',
            new_name='messenger',
        ),
    ]
