# Generated by Django 3.0.3 on 2020-06-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_auto_20200615_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='messenger',
            name='send',
            field=models.BooleanField(default=False),
        ),
    ]
