# Generated by Django 3.0.3 on 2020-07-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0006_messenger_first'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gadget',
            name='image',
            field=models.ImageField(upload_to='gadgets'),
        ),
    ]
