# Generated by Django 3.0.3 on 2020-05-17 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentReg', '0002_profile_roll_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Roll_No',
        ),
    ]
